#pragma config(Motor,  port1,           frontLeftWheel, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backLeftWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRightWheel, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           intake,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          frontRightWheel, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int MAX_SPEED = 127;
//startMotor(backLeftWheel, 127);
//startMotor(backRightWheel, 127);
//startMotor(frontLeftWheel, 127);
//startMotor(frontRightWheel, 127);
startMotor(intake, MAX_SPEED);
wait(1);
}
