#pragma config(Motor,  port1,           frontLeftWheel, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backLeftWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRightWheel, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          frontRightWheel, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

forward(127);
wait(5);

}
