#pragma config(Motor,  port1,           frontleftMotor, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backleftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backrightMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           liftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          frontrightMotor, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	//autonstart
	wait(10);
	startMotor(frontleftMotor,-127);
	startMotor(backleftMotor,-127);
	startMotor(frontrightMotor,-127);
	startMotor(backrightMotor,-127);
	wait(2);
	stopMotor(frontleftMotor);
	stopMotor(backleftMotor);
	stopMotor(frontrightMotor);
	stopMotor(backrightMotor);
	//autonend
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//remotecontrolstart
		//Right Wheels
		motor[frontrightMotor] = vexRT[Ch2];
		motor[backrightMotor]  = vexRT[Ch2];
		//Left Wheels
		motor[frontleftMotor] = vexRT[Ch3];
		motor[backleftMotor]  = vexRT[Ch3];

		//intake?
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[intakeMotor] = 127;    	//...raise the arm.
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[intakeMotor] = -127;   	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[intakeMotor] = 0;      	//...stop the arm.
		}
		//lift?
		if(vexRT[Btn6U] == 1)       	//If Button 6U is pressed...
		{
			motor[liftMotor] = 127;  		//...close the gripper.
		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
		{
			motor[liftMotor] = -127; 		//...open the gripper.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[liftMotor] = 0;    		//...stop the gripper.
		}
		//remotecontrolend
	}
}
